{"name": "test_alert3_failure", "status": "passed", "steps": [{"name": "Нажатие кнопки для вызова Alert 3", "status": "passed", "start": 1761746163785, "stop": 1761746163900}, {"name": "Отменить Cancel у Alert 3", "status": "passed", "start": 1761746163903, "stop": 1761746163908}, {"name": "Получить текст после нажатия Alert 3", "status": "passed", "start": 1761746163954, "stop": 1761746163987}, {"name": "Подтверждаем, что после нажатия Отмены у нас выпало нужное предложение", "status": "passed", "start": 1761746163987, "stop": 1761746163987}], "attachments": [{"name": "stdout", "source": "473d54ac-31e1-4624-930b-c6d3f35bbf7a-attachment.txt", "type": "text/plain"}], "start": 1761746163748, "stop": 1761746163988, "uuid": "d01635e8-3545-4d82-b7af-a13158fd3893", "historyId": "168378ac3bb54ecc85339052d470cf0c", "testCaseId": "168378ac3bb54ecc85339052d470cf0c", "fullName": "test_alerts.TestAlertsPage#test_alert3_failure", "labels": [{"name": "story", "value": "Тест второго Alert (Негативный - нажатие Отмены)"}, {"name": "feature", "value": "Alerts"}, {"name": "suite", "value": "test_alerts"}, {"name": "subSuite", "value": "TestAlertsPage"}, {"name": "host", "value": "DESKTOP-T28TT8C"}, {"name": "thread", "value": "13660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alerts"}], "titlePath": ["test_alerts.py", "TestAlertsPage"]}