{"name": "test_alert2_failure", "status": "passed", "steps": [{"name": "Нажатие кнопки для вызова Alert 2", "status": "passed", "start": 1761745519369, "stop": 1761745519481}, {"name": "Отменить Cancel у Alert 2", "status": "passed", "start": 1761745519483, "stop": 1761745519486}, {"name": "Получить текст после нажатия Alert 2", "status": "passed", "start": 1761745519520, "stop": 1761745519545}, {"name": "Подтверждаем, что после нажатия Отмены у нас выпало нужное предложение", "status": "passed", "start": 1761745519545, "stop": 1761745519545}], "attachments": [{"name": "stdout", "source": "a7544007-6331-4c55-a086-a76464c14907-attachment.txt", "type": "text/plain"}], "start": 1761745477510, "stop": 1761745519545, "uuid": "f3bd5303-aab0-4835-b94a-3497d33288d7", "historyId": "ff70814ac359c54dad1faef5f68cde8f", "testCaseId": "ff70814ac359c54dad1faef5f68cde8f", "fullName": "test_alerts.TestAlertsPage#test_alert2_failure", "labels": [{"name": "story", "value": "Тест второго Alert (Негативный - нажатие отмены)"}, {"name": "feature", "value": "Alerts"}, {"name": "suite", "value": "test_alerts"}, {"name": "subSuite", "value": "TestAlertsPage"}, {"name": "host", "value": "DESKTOP-T28TT8C"}, {"name": "thread", "value": "6204-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alerts"}], "titlePath": ["test_alerts.py", "TestAlertsPage"]}