{"name": "test_alert3_failure", "status": "passed", "steps": [{"name": "Нажатие кнопки для вызова Alert 3", "status": "passed", "start": 1761745525224, "stop": 1761745525329}, {"name": "Отменить Cancel у Alert 3", "status": "passed", "start": 1761745525331, "stop": 1761745525335}, {"name": "Получить текст после нажатия Alert 3", "status": "passed", "start": 1761745525367, "stop": 1761745525390}, {"name": "Подтверждаем, что после нажатия Отмены у нас выпало нужное предложение", "status": "passed", "start": 1761745525390, "stop": 1761745525390}], "attachments": [{"name": "stdout", "source": "0c733335-545f-4db0-b0be-e48dee489736-attachment.txt", "type": "text/plain"}], "start": 1761745525191, "stop": 1761745525391, "uuid": "e1b2006c-9a35-453a-9650-511792ccfb30", "historyId": "168378ac3bb54ecc85339052d470cf0c", "testCaseId": "168378ac3bb54ecc85339052d470cf0c", "fullName": "test_alerts.TestAlertsPage#test_alert3_failure", "labels": [{"name": "feature", "value": "Alerts"}, {"name": "story", "value": "Тест второго Alert (Негативный - нажатие Отмены)"}, {"name": "suite", "value": "test_alerts"}, {"name": "subSuite", "value": "TestAlertsPage"}, {"name": "host", "value": "DESKTOP-T28TT8C"}, {"name": "thread", "value": "4996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alerts"}], "titlePath": ["test_alerts.py", "TestAlertsPage"]}